name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'amd64'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # https://github.com/gradle/gradle-build-action
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
          gradle-version: 'current'
          #cache-read-only: false
